### PR TITLE
implement inline expressions

### PR DESCRIPTION
**Pull request by lus**
This PR tracks the progress of my attempt of implementing the inline expression system discussed in #22.

### CODE REVIEW

**Comment by zekroTJA** [comment]
I'll take a look into it tomorrow. Thank you for the PR in advance.

**Comment by lus** [comment]
Before merging we have to discuss how to implement imports.
Specifically the Go compiler raises an error if a package is imported not used.

**Comment by zekroTJA** [comment]
My proposal would be to use sort of "import declaration patterns" in the templates. These patterns are regular expressions enclosed in `§§{<regex>}` tags describing the format of an import in the specific language. Then, ranna would scan the passed `code` using the import regex and would move the imports to the right place in the template. 

Example for Go:

Spec:
```yaml
template: |-
  package main
  §§{import "[\w/]+"}
  func main() {$${CODE}}
```

Code:
```go
import "fmt"
fmt.Println("Hello World!")
```

Result:
```
package main
  import "fmt"
  func main() {fmt.Println("Hello World!")}
```

**Comment by lus** [comment]
That would be a nice solution. Could we also implement some sort of abbreviations? We could define an abbreviation pattern so that

```go
!w("fmt", "math")
fmt.Println(math.Sqrt(64.0))
```

would be a valid pattern which imports the `"fmt"` and `"math"` packages.

**Comment by zekroTJA** [comment]
> That would be a nice solution. Could we also implement some sort of abbreviations? We could define an abbreviation pattern so that
> 
> ```go
> !w("fmt", "math")
> fmt.Println(math.Sqrt(64.0))
> ```
> 
> would be a valid pattern which imports the `"fmt"` and `"math"` packages.

Well, then we would need to mark in the patterns what is content of the package name and what of the syntax. And using more complex regex patterns for imports, that would complicate that even more.

Would prefer the simple solution for now, but if you have a good idea to implement abbreviation patterns, go ahead. 😉

**Comment by lus** [comment]
Alright, then let's go with normal imports first. We can implement abbreviations later on if it's too annoying lol.

**Comment by lus** [comment]
Inline imports are implemented.

The spec now looks like this:

```yml
golang:
  image:      'golang:alpine'
  entrypoint: 'go run'
  filename:   'main.go'
  example: |-
    package main

    import "fmt"

    func main() {
    	fmt.Println("Hello world!")
    }
  inline:
    import_regex: '(?m)^import "[\w/]+"$|^import \((\n?\t?(\s+)?"[\w/]+";?)+\n?\)$'
    template: |-
      package main
      $${IMPORTS}
      func main() {$${CODE}}
```

**Pull request merged**
